### ISSUE TITLE
Cant load mame2003-plus xml

### ISSUE THREAD

**Issue by ghost** [Cpasjuste/retrofilter#1]
Hello how are you? i cant load mame 2003-plus xml from libretro github, can you please help me or fix this bug? your software looks just like something i need to make my set the best

**Comment by Cpasjuste** [comment]
Hi,

It should be fixed with latest release: https://github.com/Cpasjuste/retrofilter/releases/tag/v1.0.1

**Comment by ghost** [comment]
> Hi,
> 
> It should be fixed with latest release: https://github.com/Cpasjuste/retrofilter/releases/tag/v1.0.1

Works perfectly thank you so much, this is fantastic!
